---
apiVersion: v1
kind: Template
labels:
  template: pen-request-api-master-pipeline-template
metadata:
  name: pen-request-api-master-pipeline-template
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "pen-request-api-pipeline"
    spec:
      source:
        git:
          ref: master
          uri: "https://github.com/ndenny1/EDUC-PEN-REQUEST-API"
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: tools/Jenkins/Jenkinsfile