---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: 'educ-soam-api-template'
metadata:
  name: 'educ-soam-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: educ-soam-api-pipeline
      name: educ-soam-api-pipeline
    spec:
      source:
        contextDir: api
        git:
          ref: master
          uri: 'https://github.com/bcgov/EDUC-SOAM-API'
        type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile-api