pipeline {
  agent {
      label 'maven35'
  }
  stages {
    stage('Build App') {
      steps {
        sh "mvn -f ./api/pom.xml package"
      }
    }
    stage('Create Image Builder') {
      when {
        expression {
          openshift.withCluster() {
            return !openshift.selector("bc", "educ-soam-api-master").exists();
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.newBuild("--name=educ-soam-api-master", "--image-stream=redhat-openjdk18-openshift:1.1", "--binary")
          }
        }
      }
    }
    stage('Build Image') {
      steps {
        script {
          openshift.withCluster() {
            openshift.selector("bc", "educ-soam-api-master").startBuild("--from-file=./api/target/soam-api-0.0.1.SNAPSHOT.jar", "--wait")
            }
        }
      }
    }

  }
}